remote_theme: mpregl/Nephos-Theme
exclude:
  - readme.md
  - .github/
header_pages:
  - index.html
author: Nephos
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
